name: Docker Build

on:
  workflow_call:
    inputs:
      release:
        required: true
        type: string
      docker_tag:
        required: true
        type: string
      build_latest:
        required: false
        type: boolean
        default: true

env:
  CARGO_TERM_COLOR: always
  ECR_REPO: 288761771289.dkr.ecr.us-east-1.amazonaws.com/truth-network/node

jobs:
  docker-build:
    runs-on: gh-ubuntu-2404-x64
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3

      - name: get Node Artifact
        uses: actions/download-artifact@v4
        with:
          name: node
          path: target/release/

      - name: get Node runtime Artifact
        uses: actions/download-artifact@v4
        with:
          name: node-runtime
          path: target/release/wbuild/tnf-node-runtime/

      - name: Set 'x' rights
        run: chmod a+x target/release/tnf-node

      - name: Build the node docker images
        run: |
          docker build . --tag $ECR_REPO:${GITHUB_SHA::7} -f Containerfile

      - name: Build latest tag
        if: ${{ inputs.build_latest }}
        run: |
          docker tag $ECR_REPO:${GITHUB_SHA::7} $ECR_REPO:latest

      - name: Build docker tag, using git tag if it's a Release
        if: ${{ inputs.release == 'true'}}
        env:
          DOCKER_TAG: ${{ inputs.docker_tag }}
        run: |
          docker tag $ECR_REPO:${GITHUB_SHA::7} $ECR_REPO:$DOCKER_TAG

      - name: Login to the AWS registry
        run: |
          aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 288761771289.dkr.ecr.us-east-1.amazonaws.com

      - name: Push the images to the registry
        run: |
          docker push -a $ECR_REPO
