name: GH Release

on:
  workflow_call:
    inputs:
      repo_tag:
        required: true
        type: string
      hotfix:
        required: false
        type: boolean
        default: false

env:
  CARGO_TERM_COLOR: always

jobs:
  gh-release:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: get VoW Node Artifact
        uses: actions/download-artifact@v3
        with:
          name: vow-node
          path: target/release/

      - name: get VoW Node runtime Artifact
        uses: actions/download-artifact@v3
        with:
          name: vow-node-runtime
          path: target/release/wbuild/vow-node-runtime/

      - name: add sha256sum to files
        id: sha256
        run: |
          VOW_NODE_SHA=$(sha256sum -z target/release/vow-node | awk '{print $1}')
          WASM_SHA_RUNTIME=$(sha256sum -z target/release/wbuild/vow-node-runtime/vow_node_runtime.compact.compressed.wasm | awk '{print $1}')
          {
            echo "VOW_NODE_SHA=$VOW_NODE_SHA"
            echo "WASM_SHA_RUNTIME=$WASM_SHA_RUNTIME"
          } >> "$GITHUB_OUTPUT"

          echo "$VOW_NODE_SHA" >  target/release/vow-node.sha256
          echo "$WASM_SHA_RUNTIME" > target/release/wbuild/vow-node-runtime/vow_node_runtime.compact.compressed.wasm.sha256

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          custom_tag: ${{ inputs.repo_tag }}
          tag_prefix: ""
          github_token: ${{ env.GITHUB_TOKEN }}

      - name: Release
        if: ${{ !inputs.hotfix }}
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          tag_name: ${{ inputs.repo_tag }}
          fail_on_unmatched_files: true
          draft: false
          prerelease: false
          generate_release_notes: true
          append_body: true
          body: |
            # Release Notes
            This release contains the latest version of AvN Node Parachain.
            ## sha256sum
            vow-node: `${{ steps.sha256.outputs.VOW_NODE_SHA }}`
            vow_node_runtime.compact.compressed.wasm: `${{ steps.sha256.outputs.WASM_SHA_RUNTIME }}`
          files: |
            target/release/vow-node
            target/release/vow-node.sha256
            target/release/wbuild/vow-node-runtime/vow_node_runtime.compact.compressed.wasm
            target/release/wbuild/vow-node-runtime/vow_node_runtime.compact.compressed.wasm.sha256

      - name: Hotfix Release
        if: ${{ inputs.hotfix }}
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          tag_name: ${{ inputs.repo_tag }}
          fail_on_unmatched_files: true
          draft: false
          prerelease: true
          body: |
            # Release Notes
            This is a hotfix release of AvN Node Parachain.
            ## sha256sum
            vow-node: `${{ steps.sha256.outputs.VOW_NODE_SHA }}`
            vow_node_runtime.compact.compressed.wasm: `${{ steps.sha256.outputs.WASM_SHA_RUNTIME }}`
          files: |
            target/release/vow-node
            target/release/vow-node.sha256
            target/release/wbuild/vow-node-runtime/vow_node_runtime.compact.compressed.wasm
            target/release/wbuild/vow-node-runtime/vow_node_runtime.compact.compressed.wasm.sha256
